title: Kyle Mahre Blog
author: Kyle Mahre
email: kfmahre@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  This the professionl portfolio and blog of Kyle Mahre. I'm a freelance web developer, ultra distance runner, avid podcast
   and audiobook listener, and a graduate student at the College of William and Mary.

# social links
twitter_username: kfmahre
github_username:  kfmahre
rss: rss
# dribbble_username: jekyll
facebook_username: kmahre
# flickr_username: jekyll
instagram_username: kyle.pics.of.adventures
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
